# Generated by Django 2.2.4 on 2021-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
