# Generated by Django 2.2.4 on 2021-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='Need to Edit', max_length=200),
            preserve_default=False,
        ),
    ]
